Switch flat GH action back to deno 1.x
It fails with:

error: Requires import access to "cdn.deno.land:443", run again with the --allow-import flag
      at https://deno.land/x/flat@0.0.15/src/image.ts:1:22

Which is a newer problem that probably is in

https://github.com/githubocto/flat-postprocessing/blob/main/src/image.ts

And should be fixed there